name: Publish example site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
    
      - name: Merge main -> publish
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: 'Merge master in publish'
          from_branch: master
          target_branch: publish
          github_token: ${{ github.token }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
      - uses: actions/checkout@v2
        with: 
          ref: publish
          
      - name: Build
        run: |
          cd exampleSite
          mkdir themes
          git clone https://github.com/hugcis/hugo-astatine-theme themes/hugo-astatine-theme
          hugo --minify
          cd ../
          rm -rf docs/
          cp -r exampleSite/public docs

      - name: Publish
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update example site
          file_pattern: docs/*
