name = "smol"
license = "MIT"
licenselink = "https://github.com/colorchestra/smol/blob/master/LICENSE.md"
description = "Minimal Hugo theme using a Monospace font and without any tracking or external dependencies."
homepage = "https://github.com/colorchestra/smol"
tags = ["blog", "minimal", "monospace", "dark mode", "simple", "clean", "light", "responsive", "fast", "no-js", "no-tracking", "privacy"]
features = ["blog", "privacy", "responsive", "fast"]
min_version = "0.20"

[author]
  name = "morph"
  homepage = "morph.sh"

[original]
  author = "Vimux"
  homepage = "https://github.com/Vimux"
  repo = "https://github.com/Vimux/blank"
